version: '3'
services:

  jupyter:
    build: 
      context: .
      dockerfile: ./dockerfiles/jupyter-lab.dockerfile
    volumes:
      - .:/code
    ports:
      - 8888:8888
    environment:
      - Mongo=mongodb://root:example@mongo:27017
    depends_on:
      - mongo

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 33119:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
    depends_on:
      - mongo
