apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: dash
  name: dash
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: dash
  type: LoadBalancer